---
title: "Review Hemasphere"
author: "Paul Marcoux"
date: today
date-format: "20 02 2026"
format: 
  html:
    page-layout: full
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: true
    echo: false
    code-summary: "Show code"
    code-tools: true
    theme: cosmo
    embed-resources: true
    number-sections: true
execute:
  warning: false
  message: false
  fig-width: 6
  fig-asp: 0.618
  # fig-width: 12
  column: page
---

```{r}
#| warning: true
#| include: false
library(here)
source(here("../GlofiResistance/00_Metadata_Talyies.R"))

```

# Evolution of ICP at D6 between UT and αCD20-TCB 0,1 nM

Stats: Paired Wilcoxon test

## In CD4+ Cells

```{r}
#| echo: false
#| warning: false
data_newpatients_filter <- data_newpatients_full |> 
  filter(Pop == "CD3_CD4" & Day == "D6" & Treatment %in% c("UT","αCD20-TCB 0,1 nM"))

ggplot(data_newpatients_filter, aes(x = Treatment , y = TIGIT_Per, color = Patient_code)) +
  geom_point()+
  geom_line(aes(group= Patient_code))+
  stat_compare_means(method = "wilcox.test", paired = TRUE, aes(group = Treatment), hide.ns = FALSE, 
                       label = "p.format", size = 3, vjust = 0,label.x.npc = 'middle') + 
  labs(title = "% of CD4+ TIGIT+ at D6",
       x = "Patient Code",
       y = "Percentage of CD4+ TIGIT+") +
  theme_blood()

ggplot(data_newpatients_filter, aes(x = Treatment , y = PD1_Per, color = Patient_code)) +
  geom_point()+
  geom_line(aes(group= Patient_code))+
  stat_compare_means(method = "wilcox.test", paired = TRUE, aes(group = Treatment), hide.ns = FALSE, 
                       label = "p.format", size = 3, vjust = 0,label.x.npc = 'middle') + 
  labs(title = "% of CD4+ PD1+ at D6",
       x = "Patient Code",
       y = "Percentage of CD4+ TIGIT+") +
  theme_blood()

ggplot(data_newpatients_filter, aes(x = Treatment , y = PD1_TIGIT_Per, color = Patient_code)) +
  geom_point()+
  geom_line(aes(group= Patient_code))+
  stat_compare_means(method = "wilcox.test", paired = TRUE, aes(group = Treatment), hide.ns = FALSE, 
                       label = "p.format", size = 3, vjust = 0,label.x.npc = 'middle') + 
  labs(title = "% of CD4+ TIGIT+/PD1+ at D6",
       x = "Patient Code",
       y = "Percentage of CD4+ TIGIT+/PD1+") +
  theme_blood()

```

## In CD8+ Cells

```{r}
#| warning: false
data_newpatients_filter <- data_newpatients_full |> 
  filter(Pop == "CD3_CD8" & Day == "D6" & Treatment %in% c("UT","αCD20-TCB 0,1 nM"))

ggplot(data_newpatients_filter, aes(x = Treatment , y = TIGIT_Per, color = Patient_code)) +
  geom_point()+
  geom_line(aes(group= Patient_code))+
  stat_compare_means(method = "wilcox.test", paired = TRUE, aes(group = Treatment), hide.ns = FALSE, 
                       label = "p.format", size = 3, vjust = 0,label.x.npc = 'middle') + 
  labs(title = "% of CD8+ TIGIT+ at D6",
       x = "Patient Code",
       y = "Percentage of CD8+ TIGIT+") +
  theme_blood()

ggplot(data_newpatients_filter, aes(x = Treatment , y = PD1_Per, color = Patient_code)) +
  geom_point()+
  geom_line(aes(group= Patient_code))+
  stat_compare_means(method = "wilcox.test", paired = TRUE, aes(group = Treatment), hide.ns = FALSE, 
                       label = "p.format", size = 3, vjust = 0,label.x.npc = 'middle') + 
  labs(title = "% of CD8+ PD1+ at D6",
       x = "Patient Code",
       y = "Percentage of CD8+ TIGIT+") +
  theme_blood() 

ggplot(data_newpatients_filter, aes(x = Treatment , y = PD1_TIGIT_Per, color = Patient_code)) +
  geom_point()+
  geom_line(aes(group= Patient_code))+
  stat_compare_means(method = "wilcox.test", paired = TRUE, aes(group = Treatment), hide.ns = FALSE, 
                       label = "p.format", size = 3, vjust = 0,label.x.npc = 'middle') + 
  labs(title = "% of CD8+ TIGIT+/PD1+ at D6",
       x = "Patient Code",
       y = "Percentage of CD8+ TIGIT+/PD1+") +
  theme_blood()
```
